### PR TITLE
♻️ Handle empty title in Acknowledgements

### LINKED ISSUE #1008: ♻️  Acknowledgements - Handle empty title
Cc: @tiagov8 @sethdailyssw

Hi @Aibono1225 

### Pain
When there is no title, this code breaks and the build fails 😱
https://github.com/SSWConsulting/SSW.Rules/blob/main/src/components/acknowledgements/acknowledgements.js#L33-L36

This was an issue with a new rule.
https://github.com/SSWConsulting/SSW.Rules.Content/pull/5708

### What code could be improved?
When there is no title, handle it better.
Log a warning and just show a blank title.

```[tasklist]
### Tasks
- [ ] Improve code
``` 

Thanks!

### PR DESCRIPTION
**Pull request by Aibono1225**
Fixes #1008 

Changes I made:
- Rewrite function to handle Acknowledgements images better
- Log a warning when there is no title on the image

image

### CODE REVIEW

File: src/components/acknowledgements/acknowledgements.js [hunk 1]
```diff
@@ -19,44 +19,42 @@ const Acknowledgements = ({ authors }) => {
...
-    } else {
-      return (
-        <img src={PlaceHolderImage} alt={author.title} title={author.title} />
-      );
+  function ProfileImg({ author }) {
+    const { noimage, img, title, url } = author;
+
+    if (!title) {
+      // eslint-disable-next-line no-console
+      console.warn('Warning: Title is missing.');
```
Comment (bradystroud) [inline src/components/acknowledgements/acknowledgements.js:27]: Instead of logging this, can we add an app insights log?

Let me know if you need help with this 🙂

**Review by bradystroud — CHANGES_REQUESTED** [review]

**Comment by Aibono1225** [comment]
Hi @bradystroud ,

Now the warning log can show in the Application Insights 😊
image

**Review by bradystroud — APPROVED** [review]
💪🚀 LGTM

**Review by bradystroud — APPROVED** [review]
